### ISSUE TITLE
TOC generator seems broken when content is too long?

### ISSUE THREAD

**Issue by hanxiao** [technote-space/toc-generator#280]
## Describe the bug: バグの概要

First, thank you for providing this awesome action, we have been using it since early this year! Thanks ❤️ 🙇 

Recently, we found the TOC generator seems not to work properly anymore. In particular, on this [CHANGELOG.md](https://github.com/jina-ai/jina/blob/master/CHANGELOG.md), it stops working after 0.7.4. I suspect if the document is too long to process?

## Screenshots: スクリーンショット

**Github workflow**

https://github.com/jina-ai/jina/blob/f087726b31f8901c27cc6e27211ebd82e473f100/.github/workflows/autocommit.yml#L67-L77

Here is the dump log from Github action

```
  with:
    MAX_HEADER_LEVEL: 2
    FOLDING: false
    GITHUB_TOKEN: ***
    COMMIT_NAME: Jina Dev Bot
    COMMIT_EMAIL: dev-bot@jina.ai
    TARGET_PATHS: README*.md,CHANGELOG.md,CONTRIBUTING.md
    COMMIT_MESSAGE: chore(docs): update TOC
    OPENING_COMMENT: <!-- toc 
    CLOSING_COMMENT: <!-- tocstop 
    CREATE_PR: true
    PR_BRANCH_PREFIX: toc-generator/
    PR_BRANCH_NAME: update-toc-${PR_ID}
    PR_TITLE: docs: update TOC (${PR_MERGE_REF})
    PR_BODY: ## Base PullRequest
  
  ${PR_TITLE} (${PR_NUMBER_REF})
  
  ## Command results
  <details>
    <summary>Details: </summary>
  
    ${COMMANDS_OUTPUT}
  
  </details>
  
  ## Changed files
  <details>
    <summary>${FILES_SUMMARY}: </summary>
  
    ${FILES}
  
  </details>
  
  <hr>
  
  [:octocat: Repo](${ACTION_URL}) | [:memo: Issues](${ACTION_URL}/issues) | [:department_store: Marketplace](${ACTION_MARKETPLACE_URL})
  
    PR_COMMENT_BODY: ## Command results
  <details>
    <summary>Details: </summary>
  
    ${COMMANDS_OUTPUT}
  
  </details>
  
  ## Changed files
  <details>
    <summary>${FILES_SUMMARY}: </summary>
  
    ${FILES}
  
  </details>
  
  <hr>
  
  [:octocat: Repo](${ACTION_URL}) | [:memo: Issues](${ACTION_URL}/issues) | [:department_store: Marketplace](${ACTION_MARKETPLACE_URL})
  
    PR_CLOSE_MESSAGE: This PR has been closed because it is no longer needed.
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.7.9/x64

==================================================
Version:  technote-space/toc-generator@v2.6.1
          b1dc535f5ffbd5cd62324411eb2a1874074337e5
Event:    schedule
Action:   undefined
sha:      af9777d515ed03b8f1b6cff80545685976f8102b
ref:      refs/heads/master
owner:    jina-ai
repo:     jina

Dump context
  Context {
    payload: { schedule: '0 23 * * *' },
    eventName: 'schedule',
    sha: 'af9777d515ed03b8f1b6cff80545685976f8102b',
    ref: 'refs/heads/master',
    workflow: 'Autocommit',
    action: 'technote-spacetoc-generator',
    actor: 'hanxiao',
    job: 'autocommit',
    runNumber: 25,
    runId: 375316966
  }
Dump Payload
  { schedule: '0 23 * * *' }
==================================================
```

## Operating environment: バグが発生した環境
 - Version of software
 - OS: [e.g. Windows10]
 - Browser: [e.g. Chrome, Safari]
 - etc.

## Additional context: 補足

Mirrored: https://github.com/jina-ai/jina/issues/1321

**Comment by technote-space** [comment]
@hanxiao 
In order to avoid complicating the use of actions, it was disallowed to be triggered by `schedule` events.
In version 3, it has been changed to run on the `schedule` event.

```yaml
name: Autocommit

on:
  schedule:
    - cron: "0 23 * * *"

jobs:
  autocommit:
    if: |
      !startsWith(github.event.head_commit.message, 'chore') &&
      !startsWith(github.event.head_commit.message, 'build: hotfix') &&
      !endsWith(github.event.head_commit.message, 'reformatted by jina-dev-bot')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.JINA_DEV_BOT }}
          ref: ${{ github.event.pull_request.head.sha }}

#      ...

      - name: Generate TOC
        uses: technote-space/toc-generator@v3
        with:
          MAX_HEADER_LEVEL: 2
          # FOLDING: false  ## (default: false)
          GITHUB_TOKEN: ${{ secrets.JINA_DEV_BOT }}
          COMMIT_NAME: Jina Dev Bot
          COMMIT_EMAIL: dev-bot@jina.ai
          TOC_TITLE: ''
          TARGET_PATHS: 'README*.md,CHANGELOG.md,CONTRIBUTING.md'
          # COMMIT_MESSAGE: 'chore(docs): update TOC'  ## In v3, the default commit message has been changed to this message
          # CHECK_ONLY_DEFAULT_BRANCH: true  ## If you want not to check existing PRs
          # CREATE_PR: true ## If you want to create a PullRequest instead of committing directly

#      ...

```

[Configuration Examples](https://github.com/technote-space/toc-generator#configuration-examples)
