### ISSUE TITLE
add support for horizontal TOC

### ISSUE THREAD

**Issue by hanxiao** [technote-space/toc-generator#283]
## Please describe your suggestion: 提案の概要

TOC generator now gives vertical TOC only, would be nice to have a horizontal one

## Describe the solution you'd like: 考えうる解決方法

Add an option `HORIZONTAL_TOC` or `FLATTEN_TOC` as boolean value

Expected result:
![image](https://user-images.githubusercontent.com/2041322/100061313-293a6c00-2e2e-11eb-94ad-a04d7f2b95e4.png)

Remark: horizontal toc only makes sense when `MAX_HEADER_LEVEL = 1`

**Comment by technote-space** [comment]
related technote-space/doctoc#14

**Comment by technote-space** [comment]
@hanxiao 
I added support for horizontal TOC.

e.g. https://github.com/technote-space/toc-generator/blob/master/__tests__/fixtures/doctoc/expected/README.horizontal.md

To use it, set the `HTML_MODE` option to `true`.
https://github.com/technote-space/toc-generator#options


```yaml
      - name: Generate TOC
        uses: technote-space/toc-generator@v3
        with:
          GITHUB_TOKEN: ${{ secrets.JINA_DEV_BOT }}
          COMMIT_NAME: Jina Dev Bot
          COMMIT_EMAIL: dev-bot@jina.ai
          TOC_TITLE: ''
          TARGET_PATHS: 'CHANGELOG.md,CONTRIBUTING.md'
          CHECK_ONLY_DEFAULT_BRANCH: true  ## If you want not to check existing PRs
          HTML_MODE: true
          # HTML_TEMPLATE: <p align="center"><sub>${ITEMS}</sub></p>  ## change template
          # SEPARATOR: '･'  ## change separator
```

e.g. 

`HTML_TEMPLATE: <p align="center">${ITEMS}</p>` (default)
![スクリーンショット 2020-11-26 0 45 50](https://user-images.githubusercontent.com/39912269/100250410-fc4a9e00-2f80-11eb-956f-6958be29c0f0.png)

`HTML_TEMPLATE: <p align="center"><sub>${ITEMS}</sub></p>`
![スクリーンショット 2020-11-26 0 46 22](https://user-images.githubusercontent.com/39912269/100250426-0076bb80-2f81-11eb-85de-b43028fda227.png)

`SEPARATOR: '･'`
![スクリーンショット 2020-11-26 0 51 05](https://user-images.githubusercontent.com/39912269/100250899-8430a800-2f81-11eb-88ef-b291126b2a54.png)
