### ISSUE TITLE
The github action reports success even if it fails to push due to branch protection

### ISSUE THREAD

**Issue by hexagonrecursion** [technote-space/toc-generator#311]
## Describe the bug: バグの概要

Pushing to github can fail. One of the possible reasons if may fail is due to branch protection. When that happens `git push` returns an error code. Your action should [indicate that it failed](https://docs.github.com/en/actions/creating-actions/setting-exit-codes-for-actions) when that happens.

Example:
https://github.com/hexagonrecursion/toc-3/runs/1848107843?check_suite_focus=true#step:2:436

#### 2. Add `.github/workflows/toc.yml`
```
on:
  push:
    branches:
    - main
name: TOC Generator
jobs:
  generateTOC:
    name: TOC Generator
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/toc-generator@v3.1.4
```
#### 8. Add a `README.md`
```
# Foo
# Bar
```
## Expected behavior: 期待する動作

When a push fails due to branch protection the github action should report a failure

## Operating environment: バグが発生した環境

 - technote-space/toc-generator@v3.1.4
