### ISSUE TITLE
CREATE_PR: true shoulod work even when the job was triggered py push

### ISSUE THREAD

**Issue by hexagonrecursion** [technote-space/toc-generator#313]
## Please describe your suggestion: 提案の概要

When a branch is configured to require pull request reviews before merging, pushing to it fails (as it should). I wanted the toc generator to:
1. trigger when a commit is pushed to the default branch
1. push changes to a new branch
2. open a PR

I thought CREATE_PR: true would do exactly that:
```
on:
  push:
    branches:
    - main
name: TOC Generator
jobs:
  generateTOC:
    name: TOC Generator
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/toc-generator@v3.1.4
        with:
          CREATE_PR: true
```
but it still tries to push to the default branch https://github.com/hexagonrecursion/toc-4/runs/1848279394#step:2:432

## Describe the solution you'd like: 考えうる解決方法

technote-space/toc-generator should create a PR when CREATE_PR: true even if triggered by push. 

## Additional context: 補足

The below code is close to what I want: it opens a secondary PR when a PR is opened, but it fails when the PR is from a fork https://github.com/hexagonrecursion/toc-5/runs/1848187298?check_suite_focus=true because github (quite reasonably) does not give write access to the repo in that case.
```
on: pull_request
name: TOC Generator
jobs:
  generateTOC:
    name: TOC Generator
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/toc-generator@v3
        with:
          CREATE_PR: true
```
Using pull_request_target does bypass that, but this is considered insecure (emphasis mine):
> https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request_target
> Warning: The pull_request_target event is granted a read/write repository token and can access secrets, even when it is triggered from a fork. Although the workflow runs in the context of the base of the pull request, you should make sure that you **do not check out**, build, or run untrusted code from the pull request with this event. Additionally, any caches share the same scope as the base branch, and to help prevent cache poisoning, you should not save the cache if there is a possibility that the cache contents were altered.
```
on:
  pull_request_target:
    types: [opened, synchronize, reopened, closed]
name: TOC Generator
jobs:
  generateTOC:
    name: TOC Generator
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/toc-generator@v3
        with:
          CREATE_PR: true
```
