### ISSUE TITLE
CREATE_PR doesnt seem to be working with `on:push`

### ISSUE THREAD

**Issue by guergana** [technote-space/toc-generator#380]
## Describe the bug: バグの概要

The action creates a commit properly but given the flag CREATE_PR it doesn't create a PR with the ToC. 
This was tested when pushing to a specific folder. I don't know if the CREATE_PR flag is working when no folder is specified.

## To Reproduce: 再現手順
1. Create a workflow that uses the CREATE_PR flag:
```
 name: Update Table of Contents (ToC)

on: 
  push:
    paths: 
      - docs/**

jobs:
  generateTOC:
    name: TOC Generator
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/toc-generator@v4
        with:
          CREATE_PR: true
          TARGET_PATHS: ./docs/*.md
```
2. Push some changes to specified folder. The workflow will run and create a commit at the end of the PR that created the changes in the folder.
3. Check github, the create PR prompt is not triggered.

## Expected behavior: 期待する動作

A PR is opened with `on:push` event.

The flag works with `on:pull_request` event.

## Additional context: 補足

This was tested on the following PR: https://github.com/wmde/wikidata-mismatch-finder/pull/720
