### ISSUE TITLE
Doesn't work for github wiki edits

### ISSUE THREAD

**Issue by k9ert** [technote-space/toc-generator#382]
## Please describe your suggestion: 提案の概要
```
name: TOC Generator

on:
  gollum:  # Triggered when wiki is updated
  workflow_dispatch:  # Allow manual triggering
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight

jobs:
  generateTOC:
    name: TOC Generator
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/toc-generator@v4
        with:
          GITHUB_TOKEN: ${{ secrets.SOME_TOKEN }}
```

## Describe the solution you'd like: 考えうる解決方法
The above Action definition should add TOCs to my github wiki-pages.
Instead you get:

> This is not a target event.

## Describe alternatives you've considered: 考えうる代替案
Use a different toc-generator, e.g.
https://spinscale.de/posts/2021-10-29-github-actions-updating-github-wiki-after-edit.html
